# c?u hình
server:
  port: 8080
  servlet:
    context-path: /identity

#    c?u hình sql
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/Identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true